language: php

services:
  - mysql

addons:
  chrome: stable
  apt:
    packages:
      - dpkg
      - apache2
      - postfix
      - libapache2-mod-fastcgi
      - libappindicator1
      - fonts-liberation

cache:
  directories:
    - $HOME/.composer/cache

os: linux
dist: xenial

php:
  - 7.1

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=disabled
    - DISABLE_DEBUG_TOOLBAR=1
  jobs:
    - PRESTASHOP_TEST_TYPE=sanity

stages:
  - name: deploy
    if: type = cron
  - name: test
    if: type IN (push, pull_request)

jobs:
  include:
    - stage: deploy
      php: 7.3
      before_install: skip
      before_script: skip
      install: skip
      script:
        - mkdir -p /tmp/ps-release
        - php tools/build/CreateRelease.php --destination-dir=/tmp/ps-release
        - cd /tmp/ps-release
          && today=`date +%Y-%m-%d-`; for i in *; do mv $i $today$TRAVIS_BRANCH-$i; done
          && cd -
      if: type = cron
      deploy:
        provider: gcs
        access_key_id: $GCS_ACCESS_KEY
        secret_access_key: $GCS_ACCESS_SECRET
        bucket: prestashop-core-nightly
        acl: public-read
        local_dir: "/tmp/ps-release"
        on:
          all_branches: true

before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_10.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :10 -ac -screen 0 1600x1200x16
  # Avoid Composer authentication issues
  - if [[ "$TRAVIS_REPO_SLUG" = PrestaShop/PrestaShop ]]; then cp travis-scripts/.composer-auth.json ~/.composer/auth.json; fi;
  # Apache & php-fpm configuration
  - bash travis-scripts/setup-php-fpm.sh
  - bash travis-scripts/setup-apache.sh
  - bash travis-scripts/setup-node-js.sh

  # PrestaShop configuration
  - cp tests-legacy/parameters.yml.travis app/config/parameters.yml

  # Always test with non-unity MySQL autoincrement
  - mysql -e 'SET @@GLOBAL.auto_increment_increment = 2, @@GLOBAL.auto_increment_offset = 2;'

install:
  - composer install --ansi --prefer-dist --no-interaction --no-progress --quiet;
  - if [ "$PRESTASHOP_TEST_TYPE" = "integration" ] || [ "$PRESTASHOP_TEST_TYPE" = "sanity" ]; then
        make assets;
    fi

  - if [ "$PRESTASHOP_TEST_TYPE" != "sanity" ]; then
      bash travis-scripts/install-prestashop;
    fi

script:
  - if [ "$PRESTASHOP_TEST_TYPE" = "sanity" ]; then
        bash tests/check_sanity.sh;
    fi

after_script:
  - sudo cat /var/log/apache2/error.log

after_failure:
  - curl -L http://localhost/
  - cat /etc/apache2/envvars
  - cat /etc/apache2/sites-available/000-default.conf
  - sudo cat /var/log/php-fpm.log
  - sudo ls -l /var/log/apache2
  - sudo cat /var/log/apache2/other_vhosts_access.log
  - cat $TRAVIS_BUILD_DIR/var/log/dev.log
